name: image_frame

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install exifread pillow pyinstaller
      - run: pyinstaller -w -F image_frame.py
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
